from typing import List, Dict, Any
from app.agents.base_agent import BaseAgent

class CareerReporterAgent(BaseAgent):
    """
    AGENT 11 — CAREER REPORTER AGENT
    Compiles search metrics, deduplication counts, verification stats, and top ranked opportunities into an executive report.
    """
    def __init__(self):
        super().__init__(
            agent_name="Career Reporter Agent",
            agent_role="Executive Summary & Final Report Generator"
        )

    async def generate_report(
        self,
        mission_id: str,
        task_id: str,
        total_discovered: int,
        duplicates_removed: int,
        verified_jobs: List[Dict[str, Any]],
        platforms_searched: List[str]
    ) -> str:
        await self.log_event(mission_id, "INFO", "Compiling executive job search report...")
        await self.update_task_progress(mission_id, task_id, "RUNNING", items_count=0)

        verified_count = len(verified_jobs)
        top_matches = sorted(verified_jobs, key=lambda j: j.get("match", {}).get("match_score", 0), reverse=True)[:3]

        top_list_str = ""
        for i, j in enumerate(top_matches, 1):
            score = j.get("match", {}).get("match_score", 0)
            src = j.get("source_platform", "Web")
            top_list_str += (
                f"{i}. **{j.get('job_title')}** at **{j.get('company_name')}** ({j.get('location')})\n"
                f"   - Match: **{score}%** | Source: `{src}` | Posted: {j.get('posted_at')}\n"
                f"   - Application URL: [Apply Now]({j.get('canonical_url')})\n\n"
            )

        report = f"""# 🚀 CAREERHIVE AI — JOB SEARCH EXECUTIVE REPORT

### Search Summary
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
* **Platforms & Channels Searched**: {len(platforms_searched)} ({', '.join(platforms_searched[:4])}...)
* **Raw Job Postings Discovered**: {total_discovered}
* **Cross-Platform Duplicates Removed**: {duplicates_removed}
* **Verified Active Opportunities**: {verified_count}

### 🏆 TOP MATCHING OPPORTUNITIES

{top_list_str}

*Report generated by CEO Career AI System on behalf of candidate.*
"""

        await self.log_event(mission_id, "SUCCESS", "Executive report compiled successfully!")
        await self.update_task_progress(mission_id, task_id, "COMPLETED", items_count=1, results_summary="Report generated")
        return report

reporter_agent = CareerReporterAgent()
